export const TRACKS = [
  {
    title: 'Introduction',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/01_AYBen-001--Introduction.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 42.864,
  },
  {
    title: 'Preface',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/02_AYBen-002--Preface.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 99.72,
  },
  {
    title: 'My Parents and Early Life',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/03_AYBen-Ch01--My_Parents_and_Early_Life.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2203.68,
  },
  {
    title: 'My Mothers Death and the Mystic Amulet',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/04_AYBen-Ch02--My_Mothers_Death_and_the_Mystic_Amulet.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1197.024,
  },
  {
    title: 'The Saint With Two Bodies',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/05_AYBen-Ch03--The_Saint_With_Two_Bodies.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1118.616,
  },
  {
    title: 'My Interrupted Flight Toward the Himalayas',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/06_AYBen-Ch04--My_Interrupted_Flight_Toward_the_Himalayas.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2420.568,
  },
  {
    title: 'A Perfume Saint Displays His Wonders',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/07_AYBen-Ch05--A_Perfume_Saint_Displays_His_Wonders.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1457.112,
  },
  {
    title: 'The Tiger Swami',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/08_AYBen-Ch06--The_Tiger_Swami.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1920.36,
  },
  {
    title: 'The Levitating Saint',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/09_AYBen-Ch07--The_Levitating_Saint.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1006.2,
  },
  {
    title: 'Indias Great Scientist J. C. Bose',
    url: "https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/10_AYBen-Ch03--Indian's_Greatest_Scientist_JCBose.m4a?alt=media",
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1499.664,
  },
  {
    title: 'The Blissful Devotee and His Cosmic Romance',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/11_AYBen-Ch09--The_Blissful_Devotee_and_His_Cosmic_Romance.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2006.304,
  },
  {
    title: 'I Meet My Master Swami Sri Yukteswar',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/12_AYBen-Ch10--I_Meet_My_Master_Swami_Sri_Yukteswar.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1555.848,
  },
  {
    title: 'Two Penniless Boys in Brindaban',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/13_AYBen-Ch11--Two_Penniless_Boys_in_Brindaban.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 5826.12,
  },
  {
    title: 'Years in My Masters Hermitage',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/14_AYBen-Ch12--Years_in_My_Masters_Hermitage.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1469.76,
  },
  {
    title: 'The Sleepless Saint',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/15_AYBen-Ch13--The_Sleepless_Saint.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1624.248,
  },
  {
    title: 'An Experience in Cosmic Consciousness',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/16_AYBen-Ch14--An_Experience_in_Cosmic_Consciousness.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1921.824,
  },
  {
    title: 'The Cauliflower Robbery',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/17_AYBen-Ch15--The_Cauliflower_Robbery.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2407.56,
  },
  {
    title: 'Outwitting the Stars',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/18_AYBen-Ch16--Outwitting_the_Stars.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1257.024,
  },
  {
    title: 'Sasi and the Three Sapphires',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/19_AYBen-Ch17--Sasi_and_the_Three_Sapphires.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1103.16,
  },
  {
    title: 'A Mohammedan Wonder Worker',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/20_AYBen-Ch18--A_Mohammedan_Wonder-Worker.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 586.104,
  },
  {
    title: 'My Master in Calcutta Appears in Serampore',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/21_AYBen-Ch19--My_Master_in_Calcutta_Appears_in_Serampore.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1720.008,
  },
  {
    title: 'We Do Not Visit Kashmir',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/22_AYBen-Ch20--We_Do_Not_Visit_Kashmir.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1103.88,
  },
  {
    title: 'We Visit Kashmir',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/23_AYBen-Ch21--We_Visit_Kashmir.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1148.136,
  },
  {
    title: 'The Heart of a Stone Image',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/24_AYBen-Ch22--The_Heart_of_a_Stone_Image.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1698.36,
  },
  {
    title: 'I Receive My University Degree',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/25_AYBen-Ch23--I_Receive_My_University_Degree.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 958.056,
  },
  {
    title: 'I Become a Monk of the Swami Order',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/26_AYBen-Ch24--I_Become_a_Monk_of_the_Swami_Order.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1994.112,
  },
  {
    title: 'Brother Ananta and Sister Nalini',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/27_AYBen-Ch25--Brother_Ananta_and_Sister_Nalini.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1540.224,
  },
  {
    title: 'The Science of Kriya Yoga',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/28_AYBen-Ch26--The_Science_of_Kriya_Yoga.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 880.704,
  },
  {
    title: 'Founding a Yoga School in Ranchi',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/29_AYBen-Ch27--Founding_a_Yoga_School_in_Ranchi.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 799.656,
  },
  {
    title: 'Kashi Reborn and Discovered',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/30_AYBen-Ch28--Kashi_Reborn_and_Discovered.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2484.72,
  },
  {
    title: 'Rabindranath Tagore and I Compare Schools',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/31_AYBen-Ch29--Rabindranath_Tagore_and_I_Compare_Schools.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1501.248,
  },
  {
    title: 'The Law of Miracles',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/32_AYBen-Ch30--The_Law_of_Miracles.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 836.952,
  },
  {
    title: 'An Interview With the Sacred Mother',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/33_AYBen-Ch31--An_Interview_With_the_Sacred_Mother.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1962.264,
  },
  {
    title: 'Rama Is Raised From the Dead',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/34_AYBen-Ch32--Rama_Is_Raised_From_the_Dead.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1714.896,
  },
  {
    title: 'Babaji Yogi Christ of Modern India',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/35_AYBen-Ch33--Babaji_Yogi-Christ_of_Modern_India.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1455.816,
  },
  {
    title: 'Materializing a Palace in the Himalayas',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/36_AYBen-Ch34--Materializing_a_Palace_in_the_Himalayas.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2586.864,
  },
  {
    title: 'The Christlike Life of Lahiri Mahasaya',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/37_AYBen-Ch35--The_Christlike_Life_of_Lahiri_Mahasaya.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2118.336,
  },
  {
    title: 'Babajis Interest in the West',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/38_AYBen-Ch36--Babajis_Interest_in_the_West.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1874.952,
  },
  {
    title: 'I Go to America',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/39_AYBen-Ch37--I_Go_to_America.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1543.968,
  },
  {
    title: 'Luther Burbank A Saint Amid the Roses',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/40_AYBen-Ch38--Luther_Burbank_A_Saint_Amid_the_Roses.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 913.848,
  },
  {
    title: 'Therese Neumann the Catholic Stigmatist',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/41_AYBen-Ch39--Therese_Neumann_the_Catholic_Stigmatist.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1463.856,
  },
  {
    title: 'I Return to India',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/42_AYBen-Ch40--I_Return_to_India.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1325.496,
  },
  {
    title: 'An Idyll in South India',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/43_AYBen-Ch41--An_Idyll_in_South_India.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2420.52,
  },
  {
    title: 'Last Days With My Guru',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/44_AYBen-Ch42--Last_Days_With_My_Guru.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2718.312,
  },
  {
    title: 'The Resurrection of Sri Yukteswar',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/45_AYBen-Ch43--The_Resurrection_of_Sri_Yukteswar.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 4267.776,
  },
  {
    title: 'With Mahatma Gandhi at Wardha',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/46_AYBen-Ch44--With_Mahatma_Gandhi_at_Wardha.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 3200.712,
  },
  {
    title: 'The Bengali Joy Permeated Mother',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/47_AYBen-Ch45--The_Bengali_Joy-Permeated_Mother.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 919.752,
  },
  {
    title: 'The Woman Yogi Who Never Eats',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/48_AYBen-Ch46--The_Woman_Yogi_Who_Never_Eats.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1984.896,
  },
  {
    title: 'I Return to the West',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/49_AYBen-Ch47--I_Return_to_the_West.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 807.408,
  },
  {
    title: 'At Encinitas in California',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/50_AYBen-Ch48--At_Encinitas_in_California.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 594.24,
  },
  {
    title: 'The Years 1940 1951',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/51_AYBen-Ch49--The_Years_1940-1951.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2251.488,
  },
  {
    title: 'Afterword',
    url: 'https://firebasestorage.googleapis.com/v0/b/hello-6c55d.appspot.com/o/52_AYBen-ZZ--Afterword.m4a?alt=media',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 377.136,
  },
];

// Privacy -> https://pages.flycricket.io/yogi/privacy.html
// Terms -> https://pages.flycricket.io/yogi/terms.html
