export const TRACKS = [
  {
    title: 'Introduction',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=01_AYBen-001--Introduction.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 42.864,
  },
  {
    title: 'Preface',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=02_AYBen-002--Preface.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 99.72,
  },
  {
    title: 'My Parents and Early Life',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=03_AYBen-Ch01--My_Parents_and_Early_Life.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2203.68,
  },
  {
    title: 'My Mothers Death and the Mystic Amulet',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=04_AYBen-Ch02--My_Mothers_Death_and_the_Mystic_Amulet.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1197.024,
  },
  {
    title: 'The Saint With Two Bodies',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=05_AYBen-Ch03--The_Saint_With_Two_Bodies.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1118.616,
  },
  {
    title: 'My Interrupted Flight Toward the Himalayas',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=06_AYBen-Ch04--My_Interrupted_Flight_Toward_the_Himalayas.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2420.568,
  },
  {
    title: 'A Perfume Saint Displays His Wonders',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=07_AYBen-Ch05--A_Perfume_Saint_Displays_His_Wonders.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1457.112,
  },
  {
    title: 'The Tiger Swami',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=08_AYBen-Ch06--The_Tiger_Swami.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1920.36,
  },
  {
    title: 'The Levitating Saint',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=09_AYBen-Ch07--The_Levitating_Saint.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1006.2,
  },
  {
    title: 'Indias Great Scientist J. C. Bose',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=10_AYBen-Ch08--Indias_Great_Scientist_J._C._Bose.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1499.664,
  },
  {
    title: 'The Blissful Devotee and His Cosmic Romance',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=11_AYBen-Ch09--The_Blissful_Devotee_and_His_Cosmic_Romance.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2006.304,
  },
  {
    title: 'I Meet My Master Swami Sri Yukteswar',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=12_AYBen-Ch10--I_Meet_My_Master_Swami_Sri_Yukteswar.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1555.848,
  },
  {
    title: 'Two Penniless Boys in Brindaban',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=13_AYBen-Ch11--Two_Penniless_Boys_in_Brindaban.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 5826.12,
  },
  {
    title: 'Years in My Masters Hermitage',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=14_AYBen-Ch12--Years_in_My_Masters_Hermitage.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1469.76,
  },
  {
    title: 'The Sleepless Saint',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=15_AYBen-Ch13--The_Sleepless_Saint.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1624.248,
  },
  {
    title: 'An Experience in Cosmic Consciousness',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=16_AYBen-Ch14--An_Experience_in_Cosmic_Consciousness.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1921.824,
  },
  {
    title: 'The Cauliflower Robbery',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=17_AYBen-Ch15--The_Cauliflower_Robbery.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2407.56,
  },
  {
    title: 'Outwitting the Stars',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=18_AYBen-Ch16--Outwitting_the_Stars.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1257.024,
  },
  {
    title: 'Sasi and the Three Sapphires',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=19_AYBen-Ch17--Sasi_and_the_Three_Sapphires.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1103.16,
  },
  {
    title: 'A Mohammedan Wonder Worker',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=20_AYBen-Ch18--A_Mohammedan_Wonder-Worker.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 586.104,
  },
  {
    title: 'My Master in Calcutta Appears in Serampore',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=21_AYBen-Ch19--My_Master_in_Calcutta_Appears_in_Serampore.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1720.008,
  },
  {
    title: 'We Do Not Visit Kashmir',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=22_AYBen-Ch20--We_Do_Not_Visit_Kashmir.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1103.88,
  },
  {
    title: 'We Visit Kashmir',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=23_AYBen-Ch21--We_Visit_Kashmir.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1148.136,
  },
  {
    title: 'The Heart of a Stone Image',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=24_AYBen-Ch22--The_Heart_of_a_Stone_Image.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1698.36,
  },
  {
    title: 'I Receive My University Degree',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=25_AYBen-Ch23--I_Receive_My_University_Degree.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 958.056,
  },
  {
    title: 'I Become a Monk of the Swami Order',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=26_AYBen-Ch24--I_Become_a_Monk_of_the_Swami_Order.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1994.112,
  },
  {
    title: 'Brother Ananta and Sister Nalini',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=27_AYBen-Ch25--Brother_Ananta_and_Sister_Nalini.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1540.224,
  },
  {
    title: 'The Science of Kriya Yoga',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=28_AYBen-Ch26--The_Science_of_Kriya_Yoga.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 880.704,
  },
  {
    title: 'Founding a Yoga School in Ranchi',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=29_AYBen-Ch27--Founding_a_Yoga_School_in_Ranchi.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 799.656,
  },
  {
    title: 'Kashi Reborn and Discovered',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=30_AYBen-Ch28--Kashi_Reborn_and_Discovered.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2484.72,
  },
  {
    title: 'Rabindranath Tagore and I Compare Schools',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=31_AYBen-Ch29--Rabindranath_Tagore_and_I_Compare_Schools.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1501.248,
  },
  {
    title: 'The Law of Miracles',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=32_AYBen-Ch30--The_Law_of_Miracles.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 836.952,
  },
  {
    title: 'An Interview With the Sacred Mother',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=33_AYBen-Ch31--An_Interview_With_the_Sacred_Mother.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1962.264,
  },
  {
    title: 'Rama Is Raised From the Dead',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=34_AYBen-Ch32--Rama_Is_Raised_From_the_Dead.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1714.896,
  },
  {
    title: 'Babaji Yogi Christ of Modern India',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=35_AYBen-Ch33--Babaji_Yogi-Christ_of_Modern_India.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1455.816,
  },
  {
    title: 'Materializing a Palace in the Himalayas',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=36_AYBen-Ch34--Materializing_a_Palace_in_the_Himalayas.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2586.864,
  },
  {
    title: 'The Christlike Life of Lahiri Mahasaya',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=37_AYBen-Ch35--The_Christlike_Life_of_Lahiri_Mahasaya.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2118.336,
  },
  {
    title: 'Babajis Interest in the West',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=38_AYBen-Ch36--Babajis_Interest_in_the_West.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1874.952,
  },
  {
    title: 'I Go to America',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=39_AYBen-Ch37--I_Go_to_America.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1543.968,
  },
  {
    title: 'Luther Burbank A Saint Amid the Roses',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=40_AYBen-Ch38--Luther_Burbank_A_Saint_Amid_the_Roses.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 913.848,
  },
  {
    title: 'Therese Neumann the Catholic Stigmatist',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=41_AYBen-Ch39--Therese_Neumann_the_Catholic_Stigmatist.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1463.856,
  },
  {
    title: 'I Return to India',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=42_AYBen-Ch40--I_Return_to_India.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1325.496,
  },
  {
    title: 'An Idyll in South India',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=43_AYBen-Ch41--An_Idyll_in_South_India.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2420.52,
  },
  {
    title: 'Last Days With My Guru',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=44_AYBen-Ch42--Last_Days_With_My_Guru.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2718.312,
  },
  {
    title: 'The Resurrection of Sri Yukteswar',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=45_AYBen-Ch43--The_Resurrection_of_Sri_Yukteswar.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 4267.776,
  },
  {
    title: 'With Mahatma Gandhi at Wardha',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=46_AYBen-Ch44--With_Mahatma_Gandhi_at_Wardha.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 3200.712,
  },
  {
    title: 'The Bengali Joy Permeated Mother',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=47_AYBen-Ch45--The_Bengali_Joy-Permeated_Mother.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 919.752,
  },
  {
    title: 'The Woman Yogi Who Never Eats',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=48_AYBen-Ch46--The_Woman_Yogi_Who_Never_Eats.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 1984.896,
  },
  {
    title: 'I Return to the West',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=49_AYBen-Ch47--I_Return_to_the_West.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 807.408,
  },
  {
    title: 'At Encinitas in California',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=50_AYBen-Ch48--At_Encinitas_in_California.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 594.24,
  },
  {
    title: 'The Years 1940 1951',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=51_AYBen-Ch49--The_Years_1940-1951.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 2251.488,
  },
  {
    title: 'Afterword',
    url: 'https://audiobook.yssofindia.org/abook-bengali/download.php?salt=J4rJSPrDyBVspjFc&dfile=52_AYBen-ZZ--Afterword.mp3',
    imageUrl: 'https://yssofindia.org/audiobook/ay-bengali.jpg',
    duration: 377.136,
  },
];
